-- =========================================================
-- ECOSHARE - MINIMAL SUPABASE BACKEND
-- Paste the entire file into Supabase SQL Editor and run once.
-- =========================================================

create extension if not exists pgcrypto;

-- PROFILES
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
revoke all on table public.profiles from anon, authenticated;
grant select on table public.profiles to anon, authenticated;
grant update on table public.profiles to authenticated;

drop policy if exists "profiles_public_read" on public.profiles;
create policy "profiles_public_read" on public.profiles
for select to anon, authenticated using (true);

drop policy if exists "profiles_owner_update" on public.profiles;
create policy "profiles_owner_update" on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

-- RESOURCES
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) on delete set null,
  owner_name text not null,
  title text not null check (length(trim(title)) between 2 and 150),
  description text not null check (length(trim(description)) between 1 and 2000),
  category text not null check (category in ('electronics', 'books', 'tools', 'sports', 'others')),
  location text not null check (length(trim(location)) between 1 and 150),
  available boolean not null default true,
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.resources enable row level security;
revoke all on table public.resources from anon, authenticated;
grant select on table public.resources to anon, authenticated;
grant insert, update, delete on table public.resources to authenticated;

drop policy if exists "resources_public_read" on public.resources;
create policy "resources_public_read" on public.resources
for select to anon, authenticated using (true);

drop policy if exists "resources_owner_insert" on public.resources;
create policy "resources_owner_insert" on public.resources
for insert to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "resources_owner_update" on public.resources;
create policy "resources_owner_update" on public.resources
for update to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "resources_owner_delete" on public.resources;
create policy "resources_owner_delete" on public.resources
for delete to authenticated
using ((select auth.uid()) = owner_id);

create index if not exists resources_owner_id_idx on public.resources(owner_id);
create index if not exists resources_category_idx on public.resources(category);
create index if not exists resources_created_at_idx on public.resources(created_at desc);
grant usage, select on sequence public.resources_id_seq to authenticated;

-- BORROW REQUESTS
create table if not exists public.borrow_requests (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.resources(id) on delete cascade,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check (length(trim(message)) between 10 and 500),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table public.borrow_requests enable row level security;
revoke all on table public.borrow_requests from anon, authenticated;
grant select, insert on table public.borrow_requests to authenticated;

drop policy if exists "borrow_requester_read_own" on public.borrow_requests;
create policy "borrow_requester_read_own" on public.borrow_requests
for select to authenticated using ((select auth.uid()) = requester_id);

drop policy if exists "resource_owner_read_requests" on public.borrow_requests;
create policy "resource_owner_read_requests" on public.borrow_requests
for select to authenticated using (
  exists (
    select 1 from public.resources r
    where r.id = borrow_requests.resource_id
      and r.owner_id = (select auth.uid())
  )
);

drop policy if exists "borrow_requester_insert_own" on public.borrow_requests;
create policy "borrow_requester_insert_own" on public.borrow_requests
for insert to authenticated
with check ((select auth.uid()) = requester_id);

create index if not exists borrow_requests_requester_id_idx on public.borrow_requests(requester_id);
create index if not exists borrow_requests_resource_id_idx on public.borrow_requests(resource_id);
create index if not exists borrow_requests_status_idx on public.borrow_requests(status);
grant usage, select on sequence public.borrow_requests_id_seq to authenticated;

create unique index if not exists one_active_request_per_user_resource
on public.borrow_requests(resource_id, requester_id)
where status = 'pending';

-- AUTH -> PROFILE TRIGGER
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), 'EcoShare User')
  )
  on conflict (id) do update set full_name = excluded.full_name;
  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- BORROW VALIDATION
create or replace function public.validate_borrow_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  item_owner uuid;
  item_available boolean;
begin
  select owner_id, available into item_owner, item_available
  from public.resources
  where id = new.resource_id;

  if not found then raise exception 'Resource does not exist'; end if;
  if item_available is not true then raise exception 'Resource is currently unavailable'; end if;
  if item_owner is not null and item_owner = new.requester_id then raise exception 'You cannot request your own resource'; end if;
  if new.status <> 'pending' then raise exception 'New borrow requests must start as pending'; end if;

  return new;
end;
$$;

revoke execute on function public.validate_borrow_request() from public;
drop trigger if exists validate_borrow_request_before_insert on public.borrow_requests;
create trigger validate_borrow_request_before_insert
before insert on public.borrow_requests
for each row execute procedure public.validate_borrow_request();

-- DEMO DATA
-- PostgreSQL does not allow WHERE after VALUES, so use a conditional DO block.
do $$
begin
  if not exists (select 1 from public.resources) then
    insert into public.resources
      (owner_name, title, description, category, location, available, image_url, created_at)
    values
      ('Rahul', 'Programming Books',
       'Useful programming and computer science books for students and developers.',
       'books', 'Kottayam', true, '/assets/programming-book.jpg', '2026-09-07'),
      ('Ananya', 'Scientific Calculator',
       'Casio scientific calculator available for students and academic work.',
       'electronics', 'Kottayam', true, '/assets/calculator.jpg', '2026-09-06'),
      ('Arjun', 'Power Drill',
       'Electric power drill suitable for household repairs and DIY projects.',
       'tools', 'Kottayam', true, '/assets/power-drill.jpg', '2026-09-05'),
      ('Sneha', 'College Backpack',
       'Good condition backpack suitable for college and everyday use.',
       'others', 'Kottayam', true, '/assets/backpack.jpg', '2026-09-04');
  end if;
end;
$$;
